#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : noto-fonts
Version  : 2015.09.29.license.adobe
Release  : 1
URL      : https://github.com/googlei18n/noto-fonts/archive/v2015-09-29-license-adobe.tar.gz
Source0  : https://github.com/googlei18n/noto-fonts/archive/v2015-09-29-license-adobe.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: noto-fonts-data = %{version}-%{release}
Requires: noto-fonts-license = %{version}-%{release}
Patch1: 0001-add-noto-fontconfig-files.patch
Patch2: 0002-Add-makefile.patch

%description
![Noto](http://noto.googlecode.com/svn/wiki/images/noto.png)
# Noto fonts
Noto's goal is providing a beautiful reading experience for everyone and for all languages. With visual harmony when multiple languages share a page. With multiple styles and weights, and *Freely available to all.*

%package data
Summary: data components for the noto-fonts package.
Group: Data

%description data
data components for the noto-fonts package.


%package license
Summary: license components for the noto-fonts package.
Group: Default

%description license
license components for the noto-fonts package.


%prep
%setup -q -n noto-fonts-2015-09-29-license-adobe
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550102508
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1550102508
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/noto-fonts
cp LICENSE %{buildroot}/usr/share/package-licenses/noto-fonts/LICENSE
cp alpha/COPYING %{buildroot}/usr/share/package-licenses/noto-fonts/alpha_COPYING
cp alpha/LICENSE %{buildroot}/usr/share/package-licenses/noto-fonts/alpha_LICENSE
cp hinted/COPYING %{buildroot}/usr/share/package-licenses/noto-fonts/hinted_COPYING
cp hinted/LICENSE %{buildroot}/usr/share/package-licenses/noto-fonts/hinted_LICENSE
cp unhinted/COPYING %{buildroot}/usr/share/package-licenses/noto-fonts/unhinted_COPYING
cp unhinted/LICENSE %{buildroot}/usr/share/package-licenses/noto-fonts/unhinted_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fontconfig/conf.avail/66-noto-mono.conf
/usr/share/fontconfig/conf.avail/66-noto-sans.conf
/usr/share/fontconfig/conf.avail/66-noto-serif.conf
/usr/share/fonts/noto/Arimo-Bold.ttf
/usr/share/fonts/noto/Arimo-BoldItalic.ttf
/usr/share/fonts/noto/Arimo-Italic.ttf
/usr/share/fonts/noto/Arimo-Regular.ttf
/usr/share/fonts/noto/Cousine-Bold.ttf
/usr/share/fonts/noto/Cousine-BoldItalic.ttf
/usr/share/fonts/noto/Cousine-Italic.ttf
/usr/share/fonts/noto/Cousine-Regular.ttf
/usr/share/fonts/noto/NotoKufiArabic-Bold.ttf
/usr/share/fonts/noto/NotoKufiArabic-Regular.ttf
/usr/share/fonts/noto/NotoNaskhArabic-Bold.ttf
/usr/share/fonts/noto/NotoNaskhArabic-Regular.ttf
/usr/share/fonts/noto/NotoNaskhArabicUI-Bold.ttf
/usr/share/fonts/noto/NotoNaskhArabicUI-Regular.ttf
/usr/share/fonts/noto/NotoNastaliqUrdu-Regular.ttf
/usr/share/fonts/noto/NotoSans-Bold.ttf
/usr/share/fonts/noto/NotoSans-BoldItalic.ttf
/usr/share/fonts/noto/NotoSans-Italic.ttf
/usr/share/fonts/noto/NotoSans-Regular.ttf
/usr/share/fonts/noto/NotoSansArmenian-Bold.ttf
/usr/share/fonts/noto/NotoSansArmenian-Regular.ttf
/usr/share/fonts/noto/NotoSansAvestan-Regular.ttf
/usr/share/fonts/noto/NotoSansBalinese-Regular.ttf
/usr/share/fonts/noto/NotoSansBamum-Regular.ttf
/usr/share/fonts/noto/NotoSansBatak-Regular.ttf
/usr/share/fonts/noto/NotoSansBengali-Bold.ttf
/usr/share/fonts/noto/NotoSansBengali-Regular.ttf
/usr/share/fonts/noto/NotoSansBengaliUI-Bold.ttf
/usr/share/fonts/noto/NotoSansBengaliUI-Regular.ttf
/usr/share/fonts/noto/NotoSansBrahmi-Regular.ttf
/usr/share/fonts/noto/NotoSansBuginese-Regular.ttf
/usr/share/fonts/noto/NotoSansBuhid-Regular.ttf
/usr/share/fonts/noto/NotoSansCanadianAboriginal-Regular.ttf
/usr/share/fonts/noto/NotoSansCarian-Regular.ttf
/usr/share/fonts/noto/NotoSansCham-Bold.ttf
/usr/share/fonts/noto/NotoSansCham-Regular.ttf
/usr/share/fonts/noto/NotoSansCherokee-Regular.ttf
/usr/share/fonts/noto/NotoSansCoptic-Regular.ttf
/usr/share/fonts/noto/NotoSansCuneiform-Regular.ttf
/usr/share/fonts/noto/NotoSansCypriot-Regular.ttf
/usr/share/fonts/noto/NotoSansDeseret-Regular.ttf
/usr/share/fonts/noto/NotoSansDevanagari-Bold.ttf
/usr/share/fonts/noto/NotoSansDevanagari-Regular.ttf
/usr/share/fonts/noto/NotoSansDevanagariUI-Bold.ttf
/usr/share/fonts/noto/NotoSansDevanagariUI-Regular.ttf
/usr/share/fonts/noto/NotoSansEgyptianHieroglyphs-Regular.ttf
/usr/share/fonts/noto/NotoSansEthiopic-Bold.ttf
/usr/share/fonts/noto/NotoSansEthiopic-Regular.ttf
/usr/share/fonts/noto/NotoSansGeorgian-Bold.ttf
/usr/share/fonts/noto/NotoSansGeorgian-Regular.ttf
/usr/share/fonts/noto/NotoSansGlagolitic-Regular.ttf
/usr/share/fonts/noto/NotoSansGothic-Regular.ttf
/usr/share/fonts/noto/NotoSansGujarati-Bold.ttf
/usr/share/fonts/noto/NotoSansGujarati-Regular.ttf
/usr/share/fonts/noto/NotoSansGujaratiUI-Bold.ttf
/usr/share/fonts/noto/NotoSansGujaratiUI-Regular.ttf
/usr/share/fonts/noto/NotoSansGurmukhi-Bold.ttf
/usr/share/fonts/noto/NotoSansGurmukhi-Regular.ttf
/usr/share/fonts/noto/NotoSansGurmukhiUI-Bold.ttf
/usr/share/fonts/noto/NotoSansGurmukhiUI-Regular.ttf
/usr/share/fonts/noto/NotoSansHanunoo-Regular.ttf
/usr/share/fonts/noto/NotoSansHebrew-Bold.ttf
/usr/share/fonts/noto/NotoSansHebrew-Regular.ttf
/usr/share/fonts/noto/NotoSansHistoric-Regular.ttf
/usr/share/fonts/noto/NotoSansImperialAramaic-Regular.ttf
/usr/share/fonts/noto/NotoSansInscriptionalPahlavi-Regular.ttf
/usr/share/fonts/noto/NotoSansInscriptionalParthian-Regular.ttf
/usr/share/fonts/noto/NotoSansJavanese-Regular.ttf
/usr/share/fonts/noto/NotoSansKaithi-Regular.ttf
/usr/share/fonts/noto/NotoSansKannada-Bold.ttf
/usr/share/fonts/noto/NotoSansKannada-Regular.ttf
/usr/share/fonts/noto/NotoSansKannadaUI-Bold.ttf
/usr/share/fonts/noto/NotoSansKannadaUI-Regular.ttf
/usr/share/fonts/noto/NotoSansKayahLi-Regular.ttf
/usr/share/fonts/noto/NotoSansKharoshthi-Regular.ttf
/usr/share/fonts/noto/NotoSansKhmer-Bold.ttf
/usr/share/fonts/noto/NotoSansKhmer-Regular.ttf
/usr/share/fonts/noto/NotoSansKhmerUI-Bold.ttf
/usr/share/fonts/noto/NotoSansKhmerUI-Regular.ttf
/usr/share/fonts/noto/NotoSansLao-Bold.ttf
/usr/share/fonts/noto/NotoSansLao-Regular.ttf
/usr/share/fonts/noto/NotoSansLaoUI-Bold.ttf
/usr/share/fonts/noto/NotoSansLaoUI-Regular.ttf
/usr/share/fonts/noto/NotoSansLepcha-Regular.ttf
/usr/share/fonts/noto/NotoSansLimbu-Regular.ttf
/usr/share/fonts/noto/NotoSansLinearB-Regular.ttf
/usr/share/fonts/noto/NotoSansLisu-Regular.ttf
/usr/share/fonts/noto/NotoSansLycian-Regular.ttf
/usr/share/fonts/noto/NotoSansLydian-Regular.ttf
/usr/share/fonts/noto/NotoSansMalayalam-Bold.ttf
/usr/share/fonts/noto/NotoSansMalayalam-Regular.ttf
/usr/share/fonts/noto/NotoSansMalayalamUI-Bold.ttf
/usr/share/fonts/noto/NotoSansMalayalamUI-Regular.ttf
/usr/share/fonts/noto/NotoSansMandaic-Regular.ttf
/usr/share/fonts/noto/NotoSansMeeteiMayek-Regular.ttf
/usr/share/fonts/noto/NotoSansMongolian-Regular.ttf
/usr/share/fonts/noto/NotoSansMyanmar-Bold.ttf
/usr/share/fonts/noto/NotoSansMyanmar-Regular.ttf
/usr/share/fonts/noto/NotoSansMyanmarUI-Bold.ttf
/usr/share/fonts/noto/NotoSansMyanmarUI-Regular.ttf
/usr/share/fonts/noto/NotoSansNKo-Regular.ttf
/usr/share/fonts/noto/NotoSansNewTaiLue-Regular.ttf
/usr/share/fonts/noto/NotoSansOgham-Regular.ttf
/usr/share/fonts/noto/NotoSansOlChiki-Regular.ttf
/usr/share/fonts/noto/NotoSansOldItalic-Regular.ttf
/usr/share/fonts/noto/NotoSansOldPersian-Regular.ttf
/usr/share/fonts/noto/NotoSansOldSouthArabian-Regular.ttf
/usr/share/fonts/noto/NotoSansOldTurkic-Regular.ttf
/usr/share/fonts/noto/NotoSansOriya-Bold.ttf
/usr/share/fonts/noto/NotoSansOriya-Regular.ttf
/usr/share/fonts/noto/NotoSansOriyaUI-Bold.ttf
/usr/share/fonts/noto/NotoSansOriyaUI-Regular.ttf
/usr/share/fonts/noto/NotoSansOsmanya-Regular.ttf
/usr/share/fonts/noto/NotoSansPhagsPa-Regular.ttf
/usr/share/fonts/noto/NotoSansPhoenician-Regular.ttf
/usr/share/fonts/noto/NotoSansRejang-Regular.ttf
/usr/share/fonts/noto/NotoSansRunic-Regular.ttf
/usr/share/fonts/noto/NotoSansSamaritan-Regular.ttf
/usr/share/fonts/noto/NotoSansSaurashtra-Regular.ttf
/usr/share/fonts/noto/NotoSansShavian-Regular.ttf
/usr/share/fonts/noto/NotoSansSinhala-Bold.ttf
/usr/share/fonts/noto/NotoSansSinhala-Regular.ttf
/usr/share/fonts/noto/NotoSansSundanese-Regular.ttf
/usr/share/fonts/noto/NotoSansSylotiNagri-Regular.ttf
/usr/share/fonts/noto/NotoSansSymbols-Regular.ttf
/usr/share/fonts/noto/NotoSansSyriacEastern-Regular.ttf
/usr/share/fonts/noto/NotoSansSyriacEstrangela-Regular.ttf
/usr/share/fonts/noto/NotoSansSyriacWestern-Regular.ttf
/usr/share/fonts/noto/NotoSansTagalog-Regular.ttf
/usr/share/fonts/noto/NotoSansTagbanwa-Regular.ttf
/usr/share/fonts/noto/NotoSansTaiLe-Regular.ttf
/usr/share/fonts/noto/NotoSansTaiTham-Regular.ttf
/usr/share/fonts/noto/NotoSansTaiViet-Regular.ttf
/usr/share/fonts/noto/NotoSansTamil-Bold.ttf
/usr/share/fonts/noto/NotoSansTamil-Regular.ttf
/usr/share/fonts/noto/NotoSansTamilUI-Bold.ttf
/usr/share/fonts/noto/NotoSansTamilUI-Regular.ttf
/usr/share/fonts/noto/NotoSansTelugu-Bold.ttf
/usr/share/fonts/noto/NotoSansTelugu-Regular.ttf
/usr/share/fonts/noto/NotoSansTeluguUI-Bold.ttf
/usr/share/fonts/noto/NotoSansTeluguUI-Regular.ttf
/usr/share/fonts/noto/NotoSansThaana-Bold.ttf
/usr/share/fonts/noto/NotoSansThaana-Regular.ttf
/usr/share/fonts/noto/NotoSansThai-Bold.ttf
/usr/share/fonts/noto/NotoSansThai-Regular.ttf
/usr/share/fonts/noto/NotoSansThaiUI-Bold.ttf
/usr/share/fonts/noto/NotoSansThaiUI-Regular.ttf
/usr/share/fonts/noto/NotoSansTibetan-Bold.ttf
/usr/share/fonts/noto/NotoSansTibetan-Regular.ttf
/usr/share/fonts/noto/NotoSansTifinagh-Regular.ttf
/usr/share/fonts/noto/NotoSansUI-Bold.ttf
/usr/share/fonts/noto/NotoSansUI-BoldItalic.ttf
/usr/share/fonts/noto/NotoSansUI-Italic.ttf
/usr/share/fonts/noto/NotoSansUI-Regular.ttf
/usr/share/fonts/noto/NotoSansUgaritic-Regular.ttf
/usr/share/fonts/noto/NotoSansVai-Regular.ttf
/usr/share/fonts/noto/NotoSansYi-Regular.ttf
/usr/share/fonts/noto/NotoSerif-Bold.ttf
/usr/share/fonts/noto/NotoSerif-BoldItalic.ttf
/usr/share/fonts/noto/NotoSerif-Italic.ttf
/usr/share/fonts/noto/NotoSerif-Regular.ttf
/usr/share/fonts/noto/NotoSerifArmenian-Bold.ttf
/usr/share/fonts/noto/NotoSerifArmenian-Regular.ttf
/usr/share/fonts/noto/NotoSerifGeorgian-Bold.ttf
/usr/share/fonts/noto/NotoSerifGeorgian-Regular.ttf
/usr/share/fonts/noto/NotoSerifKhmer-Bold.ttf
/usr/share/fonts/noto/NotoSerifKhmer-Regular.ttf
/usr/share/fonts/noto/NotoSerifLao-Bold.ttf
/usr/share/fonts/noto/NotoSerifLao-Regular.ttf
/usr/share/fonts/noto/NotoSerifThai-Bold.ttf
/usr/share/fonts/noto/NotoSerifThai-Regular.ttf
/usr/share/fonts/noto/Tinos-Bold.ttf
/usr/share/fonts/noto/Tinos-BoldItalic.ttf
/usr/share/fonts/noto/Tinos-Italic.ttf
/usr/share/fonts/noto/Tinos-Regular.ttf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/noto-fonts/LICENSE
/usr/share/package-licenses/noto-fonts/alpha_COPYING
/usr/share/package-licenses/noto-fonts/alpha_LICENSE
/usr/share/package-licenses/noto-fonts/hinted_COPYING
/usr/share/package-licenses/noto-fonts/hinted_LICENSE
/usr/share/package-licenses/noto-fonts/unhinted_COPYING
/usr/share/package-licenses/noto-fonts/unhinted_LICENSE
